import { Document, Schema, model, models, Types } from "mongoose";

// Define TypeScript interface for List document
interface IList extends Document {
	user: Types.ObjectId; // Reference to User model
	name: string;
	category?: string; // Optional field
	rentPrice?: string; // Optional field
	availabilityDate?: string; // Optional field
	address?: string; // Optional field
	city?: string; // Optional field
	state?: string; // Optional field
	description?: string; // Optional field
	createdAt?: Date; // Auto-generated by Mongoose timestamps
	updatedAt?: Date; // Auto-generated by Mongoose timestamps
}

const ListSchema = new Schema<IList>(
	{
		user: {
			type: Schema.Types.ObjectId,
			required: true,
			ref: "User",
		},
		name: {
			type: String,
			required: true,
		},
		category: {
			type: String,
		},
		rentPrice: {
			type: String,
		},
		address: {
			type: String,
		},
		city: {
			type: String,
		},
		state: {
			type: String,
		},
		description: {
			type: String,
		},
		availabilityDate: {
			type: String,
		},
	},
	{ timestamps: true }
);

const List = models.List || model<IList>("List", ListSchema);

export default List;
