import { Document, Schema, Types, model, models } from "mongoose";

// Define TypeScript interface for List document
interface IList extends Document {
	user: Types.ObjectId;
	name: string;
	category: string;
	monthlyPrice: string;
	address: string;
	city: string;
	state: string;
	description: string;
	createdAt?: Date; // Auto-generated by Mongoose timestamps
	updatedAt?: Date; // Auto-generated by Mongoose timestamps
}

const ListSchema = new Schema<IList>(
	{
		user: {
			type: Schema.Types.ObjectId,
			required: true,
			ref: "User",
		},
		name: {
			type: String,
			required: true,
		},
		category: {
			type: String,
			required: true,
		},
		monthlyPrice: {
			type: String,
			required: true,
		},
		address: {
			type: String,
			required: true,
		},
		city: {
			type: String,
			required: true,
		},
		state: {
			type: String,
			required: true,
		},
		description: {
			type: String,
			required: true,
		},
	},
	{ timestamps: true }
);

const List = models.List || model<IList>("List", ListSchema);

export default List;
