import { Document, Schema, model, models } from "mongoose";

// Define TypeScript interface for User document
interface IUser extends Document {
	clerkId: string;
	email: string;
	firstName: string;
	lastName: string;
	phoneNumber?: string; // Optional field
	picture?: string; // Optional field
	gender?: string; // Optional field
	city?: string; // Optional field
	state?: string; // Optional field
	address?: string; // Optional field
	isRenter: boolean;
	isAdmin: boolean;
	dob?: string;
	createdAt?: Date; // Auto-generated by Mongoose timestamps
	updatedAt?: Date; // Auto-generated by Mongoose timestamps
}

// Define Mongoose Schema with Type Safety
const UserSchema = new Schema<IUser>(
	{
		clerkId: {
			type: String,
			required: true,
			unique: true,
		},
		email: {
			type: String,
			required: true,
			unique: true,
		},
		firstName: {
			type: String,
			required: true,
		},
		lastName: {
			type: String,
			required: true,
		},
		phoneNumber: {
			type: String,
		},
		city: {
			type: String,
		},
		state: {
			type: String,
		},
		address: {
			type: String,
		},
		dob: {
			type: String,
		},
		gender: {
			type: String,
		},
		picture: {
			type: String,
			default:
				"https://icon-library.com/images/anonymous-avatar-icon/anonymous-avatar-icon-25.jpg",
		},
		isRenter: {
			type: Boolean,
		},
		isAdmin: {
			type: Boolean,
			required: true,
			default: false,
		},
	},
	{ timestamps: true } // Enables createdAt and updatedAt
);

// Create and export the User model with Type Safety
const User = models.User || model<IUser>("User", UserSchema);

export default User;
